const router = require("express").Router();
const c = require("../controllers/friendController");
const { authMiddleware } = require("../middleware/authMiddleware");
router.get("/", authMiddleware, c.getFriends);
router.get("/requests", authMiddleware, c.getRequests);
router.get("/state/:userId", authMiddleware, c.getState);
router.post("/request", authMiddleware, c.sendRequest);
router.put("/request/:id", authMiddleware, c.respondRequest);
router.delete("/request/:id", authMiddleware, c.cancelRequest);
router.delete("/:userId", authMiddleware, c.unfriend);
module.exports = router;
